const filterTypes = {
  DISPLAY_PRODUCTS: "DISPLAY_PRODUCTS",
  BRAND: "BRAND",
  CATEGORY: "CATEGORY",
  SORT_BY: "SORT_BY",
  IN_STOCK: "IN_STOCK",
  FAST_DELIVERY: "FAST_DELIVERY",
  RATING: "RATING",
  PRICE_RANGE: "PRICE_RANGE",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

export { filterTypes };
